"""
GrandPa's Gyan - Text-to-Speech (TTS) Engine
Converts text responses to MP3 audio streams for voice output.
"""

import io
import re

def text_to_speech(text: str, lang_code: str = "en") -> io.BytesIO:
    """
    Converts input text into an in-memory MP3 audio stream.
    
    Args:
        text (str): Response string generated by the AI agent.
        lang_code (str): Language code (e.g., 'en', 'hi', 'te', 'ta').
        
    Returns:
        io.BytesIO: In-memory binary MP3 audio object ready for st.audio().
    """
    try:
        from gtts import gTTS
    except ImportError:
        from gTTS import gTTS

    # Clean markdown formatting (*, #, _, `, etc.) to ensure smooth audio narration
    clean_text = re.sub(r"[\*#_`~>\[\]\(\)]", "", text)
    clean_text = clean_text.strip()[:600]  # Limit to first 600 characters for instant voice response

    if not clean_text:
        clean_text = "Here is the response."

    # Map language preferences to gTTS supported codes
    lang_mapping = {
        "English": "en",
        "Hindi": "hi",
        "Telugu": "te",
        "Tamil": "ta",
        "Kannada": "kn",
        "Marathi": "mr"
    }
    
    target_lang = lang_mapping.get(lang_code, "en")

    mp3_fp = io.BytesIO()
    tts = gTTS(text=clean_text, lang=target_lang, slow=False)
    tts.write_to_fp(mp3_fp)
    mp3_fp.seek(0)
    
    return mp3_fp
